# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  workflow_dispatch:
  
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
      with:
        repository: dickymuliafiqri/sobatlpg
        ref: main
        token: ${{ secrets.GIT_TOKEN }}

    - name: Set up Go
      uses: actions/setup-go@v4

    - name: Build
      run: go build -o result/sobatlpg -v ./cmd/sobatlpg/main.go

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GIT_TOKEN }}
        file: result/sobatlpg
        tag: ${{ github.ref }}
        overwrite: true
