name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: release-downloader
        uses: robinraju/release-downloader@v1.12
        with:
          latest: true
          fileName: sobatlpg

      - name: Cache browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/rod
          key: ${{ runner.os }}-browser-${{ hashFiles('go.sum') }}
          restore-keys: |
            ${{ runner.os }}-browser-
  
      - name: Run
        run: ./sobatlpg
